-- 프로그래머스 그룹별 조건에 맞는 식당 목록 출력하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/131124

SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS MP
INNER JOIN REST_REVIEW AS RR
    ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE RR.MEMBER_ID IN (
    SELECT R.MEMBER_ID
    FROM (
        SELECT M.MEMBER_ID, M.MEMBER_NAME, COUNT(M.MEMBER_ID) AS CNT,
            RANK() OVER (ORDER BY COUNT(M.MEMBER_ID) DESC) AS RANKING
        FROM MEMBER_PROFILE AS M
        INNER JOIN REST_REVIEW AS R
            ON M.MEMBER_ID = R.MEMBER_ID
        GROUP BY M.MEMBER_ID, M.MEMBER_NAME) AS R
    WHERE R.RANKING = 1
)
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT