-- 코드를 입력하세요
SELECT YEAR(S.SALES_DATE) AS YEAR, 
          MONTH(S.SALES_DATE) AS MONTH,
          COUNT(DISTINCT S.USER_ID) AS PUCHASED_USERS,
          ROUND(COUNT(DISTINCT S.USER_ID) / 
            (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
    FROM USER_INFO I
    LEFT JOIN ONLINE_SALE S
    ON I.USER_ID = S.USER_ID
    WHERE I.JOINED LIKE '2021%' AND S.SALES_DATE LIKE '2022%' 
    -- 2022년 구매 조건을 안넣으면 YEAR과 MONTH열이 NULL인 행이 출력됨..
    GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
    ORDER BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
