# Table 1: USED_GOODS_BOARD

# Table 2: USED_GOODS_USER

# Task: 
# 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 2.USER_ID, 2.NICKNAME, 총거래금액을 조회
    # 결과는 총거래금액을 기준으로 오름차순 정렬

SELECT U.USER_ID, U.NICKNAME, SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_USER as U
RIGHT JOIN USED_GOODS_BOARD as B
    on U.USER_ID = B.WRITER_ID
WHERE STATUS = 'DONE'

GROUP BY U.USER_ID
HAVING TOTAL_SALES >= 700000

ORDER BY TOTAL_SALES ASC
