-- # ITEM_INFO: 게임에서 사용되는 아이템 정보
-- # ITEM_TREE: 아이템 관계

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO main
WHERE ITEM_ID NOT in (
    SELECT DISTINCT PARENT_ITEM_ID
    FROM ITEM_TREE t
    WHERE PARENT_ITEM_ID IS NOT NULL # 이거 안 하면, NOT IN에 아무것도 안 걸리네
    ) 
ORDER BY ITEM_ID DESC
