SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS, ROUND(avg(b.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS a JOIN REST_REVIEW AS b
ON a.REST_ID = b.REST_ID
GROUP BY b.REST_ID
HAVING a.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC
