-- 코드를 입력하세요
SELECT
    RI.REST_ID,
    RI.REST_NAME,
    RI.FOOD_TYPE,
    RI.FAVORITES,
    RI.ADDRESS,
    ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE -- 소수점 3에서 2로 반올림
FROM
    REST_INFO RI
LEFT JOIN
    REST_REVIEW RR ON RI.REST_ID = RR.REST_ID
WHERE
    RI.ADDRESS LIKE '서울%' -- 서울특별시와 서울은 다른 곳이니까 음..
GROUP BY
    RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS
HAVING
    AVG(RR.REVIEW_SCORE) IS NOT NULL
ORDER BY
    SCORE DESC,
    RI.FAVORITES DESC;
