# Table 1: FOOD_PRODUCT

# Table 2: FOOD_ORDER

# FOOD_PRODUCT와 FOOD_ORDER 테이블에서 생산일자가 2022년 5월인 식품들의 PRODUCT_ID, PRODUCT_NAME, 총매출을 조회하는 SQL문을 작성
    # 결과는 총매출을 기준으로 내림차순 정렬해주시고 총매출이 같다면 식품 ID를 기준으로 오름차순 정렬
    
SELECT o.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT * PRICE) as TOTAL_SALES
# FROM FOOD_PRODUCT
FROM FOOD_ORDER as o
JOIN FOOD_PRODUCT as p on o.PRODUCT_ID = p.PRODUCT_ID
    
    WHERE MONTH(PRODUCE_DATE) = 5

GROUP BY PRODUCT_ID
    
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
