-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME,
    SUM(O.AMOUNT * P.PRICE) AS TOTAL_SALES -- 총매출=주문량*가격
FROM FOOD_ORDER O
JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE EXTRACT(YEAR FROM O.PRODUCE_DATE) = 2022 AND EXTRACT(MONTH FROM O.PRODUCE_DATE)=5 -- 2022년, 5월 Date 정보 각각
GROUP BY
    P.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    P.PRODUCT_ID ASC;
