SELECT DATE_FORMAT(f.START_DATE, '%c') MONTH, f.CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY f,
     (SELECT CAR_ID, COUNT(*) TOTAL
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE START_DATE >= '2022-08-01' AND
            START_DATE <= '2022-10-31'
      GROUP BY CAR_ID
      HAVING COUNT(*) >= 5) s
WHERE f.CAR_ID = s.CAR_ID
GROUP BY DATE_FORMAT(f.START_DATE, '%c'), f.CAR_ID
HAVING COUNT(*) > 0
ORDER BY MONTH, CAR_ID DESC;

-- SELECT DATE_FORMAT(START_DATE, '%m') MONTH, CAR_ID, COUNT(*) RECORDS
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE CAR_ID = (SELECT CAR_ID
--                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--                WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
--                GROUP BY CAR_ID
--                HAVING COUNT(*) >= 5)
-- GROUP BY DATE_FORMAT(START_DATE, '%m'), CAR_ID
-- ORDER BY MONTH, CAR_ID DESC;
