SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE)>=8 AND MONTH(START_DATE)<=10 AND CAR_ID IN (SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE)>=8 AND MONTH(START_DATE)<=10
          GROUP BY CAR_ID
           HAVING COUNT(CAR_ID) >=5)
GROUP BY MONTH(START_DATE), CAR_ID
HAVING RECORDS >= 1
ORDER BY MONTH, CAR_ID DESC;
