-- 코드를 입력하세요
-- https://school.programmers.co.kr/learn/courses/30/lessons/131120

SELECT MEMBER_ID, 
       MEMBER_NAME, 
       GENDER, 
       DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") as DATE_OF_BIRTH
# SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_ADD(DATE_OF_BIRTH, INTERVAL 1 YEAR), "%Y-%m-%d") as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH)=3 
      AND TLNO IS NOT NULL 
      AND GENDER = "W"
ORDER BY MEMBER_ID