-- 프로그래머스 카테고리 별 도서 판매량 집계하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/144855

SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK AS B
LEFT JOIN BOOK_SALES AS S
    ON B.BOOK_ID = S.BOOK_ID
WHERE MONTH(S.SALES_DATE) = 1
GROUP BY B.CATEGORY
ORDER BY CATEGORY