SELECT A.CAR_ID, A.CAR_TYPE, ROUND(DAILY_FEE*30*((100 - DISCOUNT_RATE)/100),0)  AS "FEE" 
-- 반올림을 통한 정수형 변환
FROM (SELECT * FROM CAR_RENTAL_COMPANY_CAR 
WHERE CAR_TYPE IN ("세단", "SUV")) AS A
-- 인라인 뷰 
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
ON A.CAR_TYPE = B.CAR_TYPE AND DURATION_TYPE = "30일 이상"
-- "30일 이상" 의 조건까지 같이 걸어줘야함
WHERE CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                     WHERE ("2022-11-01" BETWEEN START_DATE AND END_DATE)
        OR ("2022-11-31" BETWEEN START_DATE AND END_DATE)) 
        
-- 11월 동안 대여되지 않은 것을 찾아야 하므로 NOT IN (SELECT B.CAR_ID 사용)
GROUP BY CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000

ORDER BY FEE DESC, A.CAR_TYPE ASC, CAR_ID DESC;
