-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, 
          ROUND(C.DAILY_FEE*30*(1-D.DISCOUNT_RATE/100)) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
        LEFT OUTER JOIN 
            (SELECT CAR_TYPE, DISCOUNT_RATE
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                    WHERE DURATION_TYPE = '30일 이상') D
            ON C.CAR_TYPE = D.CAR_TYPE
    WHERE C.CAR_ID NOT IN
        (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
-- 시작일이나 종료일이 11월에 있는 경우, 11월 전에 빌려 11월 이후에 반납하는 경우를 제외
         WHERE (START_DATE BETWEEN '2022-11-01' AND '2022-11-30')
            OR (END_DATE BETWEEN '2022-11-01' AND '2022-11-30')
            OR (START_DATE < '2022-11-01' AND END_DATE > '2022-11-30'))
        AND (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
    GROUP BY C.CAR_ID
    HAVING FEE >= 500000 AND FEE < 2000000
    ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
