WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT s.ID, s.PARENT_ID, f.GENERATION + 1 GENERATION
    FROM CTE f, ECOLI_DATA s
    WHERE f.ID = s.PARENT_ID
    )
    
SELECT COUNT(*) COUNT, GENERATION
FROM CTE
WHERE ID NOT IN (SELECT PARENT_ID
                 FROM ECOLI_DATA
                 WHERE PARENT_ID IS NOT NULL) -- 그런데 왜 NULL을 제거해야만 하는것인지?
GROUP BY GENERATION
ORDER BY GENERATION ;
