-- 질문하기를 참고했습니다:( 
-- 재귀 함수 통해서 GENERATION 정의
WITH RECURSIVE GENERATION AS
(
  SELECT
    ID,
    PARENT_ID,
    1 AS GENERATION
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NULL

  UNION ALL

  SELECT
    A.ID,
    A.PARENT_ID,
    G.GENERATION + 1 AS GENERATION
  FROM
    ECOLI_DATA AS A
  JOIN GENERATION AS G 
    ON A.PARENT_ID = G.ID
)

-- 세대 데이터와 부모 아이디를 LEFT JOIN 하고 위에서 정의한 GENERATION 활용 그룹화
SELECT
  COUNT(G.ID) AS 'COUNT',
  G.GENERATION AS 'GENERATION'
FROM GENERATION AS G
LEFT JOIN ECOLI_DATA AS A ON G.ID = A.PARENT_ID
WHERE A.PARENT_ID IS NULL
GROUP BY GENERATION
