WITH RECURSIVE cte_gen
AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT a.ID, a.PARENT_ID, cte_gen.GENERATION + 1
    FROM ECOLI_DATA AS a
    JOIN cte_gen
    ON a.PARENT_ID = cte_gen.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM cte_gen
WHERE cte_gen.ID NOT IN (SELECT DISTINCT(PARENT_ID)
                        FROM cte_gen
                        WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION
