 -- 코드를 입력하세요
SELECT J.FLAVOR
    FROM(SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS 'TOTAL_ORDER'
        FROM JULY 
        GROUP BY FLAVOR) J
    INNER JOIN FIRST_HALF F
        ON J.FLAVOR = F.FLAVOR
        ORDER BY F.TOTAL_ORDER +  J.TOTAL_ORDER  DESC
        LIMIT 3;
